/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"
#include "spi.h"
#include "gpio.h"

uint8_t tx = 0x01;

void Delay(void){
	for(volatile uint32_t i = 0; i < 500000; i++);
}

void SPI2_GPIO_Init(void){
	GPIO_Handle_t spi2_gpio;

	spi2_gpio.pGPIOx = GPIOB;

	GPIO_ClockControl(GPIOB, ENABLE);

	spi2_gpio.GPIOx_CFG.pin_mode = GPIO_MODE_ALT_FN;
	spi2_gpio.GPIOx_CFG.pin_alt_func_mode = 5;
	spi2_gpio.GPIOx_CFG.pin_op_type = GPIO_OUT_PP;
	spi2_gpio.GPIOx_CFG.pin_pu_pd_ctrl = GPIO_NO_PUPD;
	spi2_gpio.GPIOx_CFG.pin_speed = GPIO_OSPEED_HIGH;

	//SCLK
	spi2_gpio.GPIOx_CFG.pin_number = GPIO_PIN_13;
	GPIO_Init(&spi2_gpio);

	//MOSI
	spi2_gpio.GPIOx_CFG.pin_number = GPIO_PIN_15;
	GPIO_Init(&spi2_gpio);

	//MISO
	spi2_gpio.GPIOx_CFG.pin_number = GPIO_PIN_14;
	GPIO_Init(&spi2_gpio);

	//NSS
	spi2_gpio.GPIOx_CFG.pin_mode = GPIO_MODE_OUT;
	spi2_gpio.GPIOx_CFG.pin_number = GPIO_PIN_12;
	GPIO_Init(&spi2_gpio);
}

void SPI2_Init(void){
	SPI_Handle_t spi2;

	spi2.pSPIx = SPI2;
	SPI_ClockControl(SPI2, ENABLE);

	spi2.SPI_Configs.spi_bus_config = SPI_BUS_CFG_FD;
	spi2.SPI_Configs.spi_device_mode = SPI_DEVICE_MODE_MASTER;
	spi2.SPI_Configs.spi_clock_speed = SPI_SCLK_SPEED_DIV8;
	spi2.SPI_Configs.spi_dff = SPI_DFF_8B;
	spi2.SPI_Configs.spi_cpol = SPI_CPOL_LOW;
	spi2.SPI_Configs.spi_cpha = SPI_CPHA_LOW;
	spi2.SPI_Configs.spi_ssm = SPI_SSM_EN;
	spi2.SPI_Configs.spi_ssi = SPI_SSI_EN;

	SPI_Init(&spi2);
}

int main(void){
	SPI2_GPIO_Init();
	SPI2_Init();

	SPI_PeripheralControl(SPI2, ENABLE);

	GPIO_WritePin(GPIOB, GPIO_PIN_12, RESET);

	while(SPI_GetFlagStatus(SPI2, SPI_TXE_FLAG) == RESET);

	SPI_Data_Transmit(SPI2, &tx, 1);

	while(SPI_GetFlagStatus(SPI2, SPI_BUSY_FLAG) == SET);

	GPIO_WritePin(GPIOB, GPIO_PIN_12, SET);

	SPI_PeripheralControl(SPI2, DISABLE);

	while(1);
}
